messaging:
  tweets:                             # queue name
    TweetProcessor:                   # processor class name
      selector: "language = 'java'"     # JMS message selector

jobs:
  tweet_remover:
    job:  TweetRemover
    cron: '*/30 * * * * ?'

